encoding: utf-8

name: I WROTE CSS WITH YOUR MOTHER LAST SUMMER

permalink: /:title/

markdown: kramdown

baseurl: /blog
url: ikniaziuk.github.io
title: I WROTE CSS WITH YOUR MOTHER LAST SUMMER
description: Сборник кустарных CSS, HTML, JS рецептов для приготовлния твоего персонального коктейля.

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
