encoding: utf-8

name: I WROTE CSS WITH YOUR MOTHER LAST SUMMER

permalink: /:title/

markdown: kramdown

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock