encoding: utf-8

exclude: ['node_modules', 'gulpfile.js', 'package.json']

name: I WROTE CSS WITH YOUR MOTHER LAST SUMMER

permalink: /:title/

domain: iwrotecsswithyourmotherlastsummer.ru
url: http://iwrotecsswithyourmotherlastsummer.ru/