encoding: utf-8

name: I WROTE CSS WITH YOUR MOTHER LAST SUMMER

permalink: /:title/

markdown: kramdown

domain: iwrotecsswithyourmotherlastsummer.ru
url: http://iwrotecsswithyourmotherlastsummer.ru/
title: I WROTE CSS WITH YOUR MOTHER LAST SUMMER
description: Сборник кустарных CSS, HTML, JS рецептов для приготовлния твоего персонального коктейля.

exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock